name: enigmo_server
description: Enigmo Bootstrap Server — lightweight WS/REST signaling and message relay
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  crypto: ^3.0.6
  cryptography: ^2.5.0
  uuid: ^4.5.1
  args: ^2.6.0
  logging: ^1.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
